### ISSUE TITLE
Host self-hosting-101.pipal.in

### ISSUE THREAD

**Issue by anandology** [pipalacademy/self-hosting-101#4]
Deploy self-hosting-101 project and setup github actions to update it automatically.

**Comment by anandology** [comment]
We have the following options for the URL. Which one shall we pick?

```
selfhosting.club/selfhosting
selfhosting.club/self-hosting-101
selfhosting.pipal.in
self-hosting-101.pipal.in
```

**Comment by nikochiko** [comment]
> Deploy self-hosting-101 project and setup github actions to update it automatically.

Both are done. Deployment is done with Hamr, so the build.sh script can be modified to add more one-time tasks on-push.

build.sh currently has one line script to run schema.sql on the treadmill.db database. We need to be careful about the migrations, if there are changes to an existing table they won't go through automatically and we'd have to SSH in and then complete the migrations.
